//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESS_SETRECONDUALUPLD
    {
        public string PID { get; set; }
        public string REFERENCENO { get; set; }
        public string CARDTYPE { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public Nullable<System.DateTime> TRANSACTIONDATETIME { get; set; }
        public Nullable<System.DateTime> SETTLEMENTDATE { get; set; }
        public string MASKEDPAN { get; set; }
        public string MERCHANTID { get; set; }
        public string MERCHANTACCOUNT { get; set; }
        public string MERCHANTNAME { get; set; }
        public string MERCHANTLOCATION { get; set; }
        public string TERMINALID { get; set; }
        public Nullable<decimal> TRANAMOUNT { get; set; }
        public Nullable<decimal> AMOUNTCHARGED { get; set; }
        public Nullable<decimal> SETTLEMENTAMOUNT { get; set; }
        public Nullable<decimal> MSCRATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string BATCHID { get; set; }
        public string USERID { get; set; }
        public Nullable<int> PostSequence { get; set; }
        public Nullable<bool> VALIDATIONERRORSTATUS { get; set; }
        public string VALIDATIONERRORMESSAGE { get; set; }
        public string WARNINGMESSAGE { get; set; }
        public Nullable<int> reconcile { get; set; }
        public string BATCHTYPE { get; set; }
    }
}
