//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_ASPNETUSERSTEMP
    {
        public int ItbId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int RoleId { get; set; }
        public bool ForcePassword { get; set; }
        public bool IsApproved { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string RoleName { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public int InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> EnforcePasswordChangeDays { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RecordId { get; set; }
        public bool Supervisor { get; set; }
    }
}
