//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_BL_FEE1SHARINGPARTY
    {
        public decimal ITBID { get; set; }
        public string BILLER_CODE { get; set; }
        public Nullable<decimal> BILLERMSC_ITBID { get; set; }
        public Nullable<int> PARTYITBID { get; set; }
        public string PARTY_LOCATOR { get; set; }
        public Nullable<decimal> SHARINGVALUE { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string LASTMODIFIED_UID { get; set; }
        public string PARTYTYPE_CODE { get; set; }
    
        public virtual SM_BILLERMSC SM_BILLERMSC { get; set; }
    }
}
