//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_BILLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_BILLER()
        {
            this.SM_BILLERACCOUNT = new HashSet<SM_BILLERACCOUNT>();
        }
    
        public decimal ITBID { get; set; }
        public string BILLER_CODE { get; set; }
        public string BILLER_DESC { get; set; }
        public string BILLER_SHORTNAME { get; set; }
        public Nullable<int> SERVICETYPE { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public string MERCHANTID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public string BATCHID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_BILLERACCOUNT> SM_BILLERACCOUNT { get; set; }
    }
}
