//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_BILLERMSC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_BILLERMSC()
        {
            this.SM_BL_FEE1SHARINGPARTY = new HashSet<SM_BL_FEE1SHARINGPARTY>();
        }
    
        public decimal ITBID { get; set; }
        public string BILLER_CODE { get; set; }
        public string MERCHANTID { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public string CBN_CODE { get; set; }
        public Nullable<decimal> FEE1 { get; set; }
        public Nullable<decimal> FEE2 { get; set; }
        public Nullable<decimal> DOM_MSC1 { get; set; }
        public Nullable<decimal> DOM_MSC2 { get; set; }
        public Nullable<decimal> DOM_CAP { get; set; }
        public Nullable<decimal> DOM_UNSHAREDMSC { get; set; }
        public Nullable<decimal> DOM_UNSHAREDCAP { get; set; }
        public string DOM_MSC_CALCBASIS { get; set; }
        public Nullable<decimal> DOM_MSCSUBSIDY { get; set; }
        public Nullable<decimal> UNSHAREDFEE1 { get; set; }
        public string FEE_CALCBASIS { get; set; }
        public string FEE2_CALCBASIS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_BL_FEE1SHARINGPARTY> SM_BL_FEE1SHARINGPARTY { get; set; }
    }
}
