//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_COMPANY_PROFILETEMP
    {
        public int ITBID { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string COMPANY_WEBSITE { get; set; }
        public string COMPANY_PHONE1 { get; set; }
        public string COMPANY_PHONE2 { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_COUNTRY { get; set; }
        public string COMPANY_STATE { get; set; }
        public string COMPANY_CITY { get; set; }
        public Nullable<int> PASSWORD_CHANGE_DAYS { get; set; }
        public Nullable<int> SYSTEM_IDLE_TIMEOUT { get; set; }
        public Nullable<int> LOCKOUT_TRIAL_COUNT { get; set; }
        public Nullable<int> RECORDID { get; set; }
        public Nullable<int> PASSWORDLENGTH { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> WHTAXRATE { get; set; }
        public string WHTACCOUNT { get; set; }
        public string WHTBANKCODE { get; set; }
        public Nullable<decimal> NIBSSRATE { get; set; }
        public string NIBSSACCOUNT { get; set; }
        public string NIBSSBANKCODE { get; set; }
    }
}
