//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_COMPANY_PROFILE
    {
        public int ITBID { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string COMPANY_WEBSITE { get; set; }
        public string COMPANY_PHONE1 { get; set; }
        public string COMPANY_PHONE2 { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_COUNTRY { get; set; }
        public string COMPANY_STATE { get; set; }
        public string COMPANY_CITY { get; set; }
        public Nullable<int> PASSWORD_CHANGE_DAYS { get; set; }
        public Nullable<int> SYSTEM_IDLE_TIMEOUT { get; set; }
        public Nullable<int> LOCKOUT_TRIAL_COUNT { get; set; }
        public Nullable<int> PASSWORDLENGTH { get; set; }
        public Nullable<decimal> DEFAULT_SHARING { get; set; }
        public string PROCESS_ERRORFLAG { get; set; }
        public Nullable<System.DateTime> OPDATETIME { get; set; }
        public Nullable<System.DateTime> CPDDATETIME { get; set; }
        public string PROCESS_FLAG { get; set; }
        public Nullable<decimal> BATCHNO { get; set; }
        public Nullable<System.DateTime> SETTDATETIME { get; set; }
        public string LASTDOCNO { get; set; }
        public Nullable<decimal> CODE { get; set; }
        public Nullable<System.DateTime> PROCESS_STARTS { get; set; }
        public Nullable<System.DateTime> PROCESS_END { get; set; }
        public Nullable<decimal> PROCESS_SETTCOUNT { get; set; }
        public Nullable<decimal> PROCESS_MEBCOUNT { get; set; }
        public Nullable<decimal> DEFAULT_SHARINGCAP { get; set; }
        public Nullable<decimal> NIBBS_COUNT { get; set; }
        public string NIBSS_DEFAULTDR { get; set; }
        public string NIBSS_DEFAULTCR { get; set; }
        public string NIBSS_DEFAULTDRBANK { get; set; }
        public string NIBSS_DEFAULTCRBANK { get; set; }
        public string NIBSS_DEFAULTDRBANKCODE { get; set; }
        public string NIBSS_DEFAULTCRBANKCODE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<decimal> WHTAXRATE { get; set; }
        public string WHTACCOUNT { get; set; }
        public Nullable<decimal> NIBSSRATE { get; set; }
        public string NIBSSACCOUNT { get; set; }
        public string NIBSSBANKCODE { get; set; }
        public string WHTBANKCODE { get; set; }
        public string PROCESS_FLAG_NAPS { get; set; }
        public Nullable<int> SETTLEMENTOPTION { get; set; }
    }
}
