//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_DATABIN
    {
        public decimal ITBID { get; set; }
        public string CBNCODE { get; set; }
        public string CARDSCHEME { get; set; }
        public string BIN { get; set; }
        public string COUNTRYCODE { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<decimal> BANKFIID { get; set; }
        public string BUSINESSTYPE { get; set; }
        public string ISSUERFIID { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
