//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_EXCHANGERATE
    {
        public int ITBID { get; set; }
        public Nullable<int> INSTITUTION_ITBID { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> NAIRA_EQUIVALENT { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string STATUS { get; set; }
        public string CBN_CODE { get; set; }
        public string CARDSCHEME { get; set; }
    }
}
