//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_INSTITUTIONACCTTEMP
    {
        public int ITBID { get; set; }
        public string CARDSCHEME { get; set; }
        public Nullable<int> INSTITUTION_ITBID { get; set; }
        public string DEPOSIT_BANKCODE { get; set; }
        public string DEPOSIT_ACCOUNTNO { get; set; }
        public string DEPOSIT_BANKNAME { get; set; }
        public string DEPOSIT_COUNTRYCODE { get; set; }
        public string DEPOSIT_BANKADDESS { get; set; }
        public Nullable<bool> DEFAULT_ACCOUNT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> RECORDID { get; set; }
        public string BATCHID { get; set; }
        public string DEPOSIT_ACCTNAME { get; set; }
        public string EVENTTYPE { get; set; }
        public string DEPOSIT_BANKADDRESS { get; set; }
    }
}
