//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_INSTITUTIONTEMP
    {
        public int ITBID { get; set; }
        public string CBN_CODE { get; set; }
        public string INSTITUTION_NAME { get; set; }
        public string INSTITUTION_SHORTCODE { get; set; }
        public string EMAIL { get; set; }
        public string PHONENO { get; set; }
        public string INSTITUTION_URL { get; set; }
        public string INSTITUTION_ADDRESS { get; set; }
        public string INSTITUTION_COUNTRY { get; set; }
        public string INSTITUTION_STATE { get; set; }
        public string INSTITUTION_CITY { get; set; }
        public string INSTITUTION_SLOGAN { get; set; }
        public string BUSINESS_ID { get; set; }
        public string IS_BANK { get; set; }
        public string BANK_SECTOR { get; set; }
        public string IS_ACQUIRER { get; set; }
        public string IS_ISSUER { get; set; }
        public string IS_COACQUIRER { get; set; }
        public string ISSUER_NIBSSACCOUNT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> RECORDID { get; set; }
        public string BATCHID { get; set; }
        public Nullable<decimal> INSTITUTION_ID { get; set; }
        public string PTSP { get; set; }
        public string ACQUIRING_TYPE { get; set; }
        public string POS_LASTMID_GENERATED { get; set; }
        public string SM_INSTITUTIONTEMP1 { get; set; }
        public string WEB_LASTMID_GENERATED { get; set; }
        public string WEB_LASTTID_GENERATED { get; set; }
        public string FIRST_TIER_XML { get; set; }
        public string SECOND_TIER_XML { get; set; }
        public string BRANCH_PART_XML { get; set; }
        public string START_ACCNO_XML { get; set; }
        public string XMLCONFIGSTATUS { get; set; }
        public string CURRENCY_XML { get; set; }
        public string START_TWCMSID_XML { get; set; }
        public string LAST_START_TWCMSID_XML { get; set; }
    }
}
