//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MENUCONTROL
    {
        public int MENUID { get; set; }
        public string MENUNAME { get; set; }
        public string CONTROLLER { get; set; }
        public string URL { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string STATUS { get; set; }
        public Nullable<bool> FLAG { get; set; }
        public string RESOURCEKEY { get; set; }
        public Nullable<short> NO_OF_CHECKER { get; set; }
        public string App { get; set; }
    }
}
