//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MERCHANTDETAILTEMP
    {
        public decimal ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public string MERCHANTNAME { get; set; }
        public string CONTACTTITLE { get; set; }
        public string CONTACTNAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONENO { get; set; }
        public string ADDRESS { get; set; }
        public string BUSINESS_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string CITY_NAME { get; set; }
        public string MCC_CODE { get; set; }
        public string ACCEPTANCE_TYPE { get; set; }
        public string TMS_OWNERCODE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public Nullable<decimal> RECORDID { get; set; }
        public string RULE_OPTION { get; set; }
        public string INSTITUTION_CBNCODE { get; set; }
        public string CALC_BASIS { get; set; }
        public Nullable<int> COLLECTION { get; set; }
        public string OLD_MID { get; set; }
        public Nullable<int> SETTLEMENT_FREQUENCY { get; set; }
        public Nullable<int> SET_DATE_TERM { get; set; }
        public Nullable<int> SET_DAYS { get; set; }
    }
}
