//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MENUPRIVTEMP
    {
        public int ITBID { get; set; }
        public Nullable<int> MENUID { get; set; }
        public string App { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string EVENTTYPE { get; set; }
    }
}
