//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MERCHANTMSCTEMP
    {
        public decimal ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public string MCC { get; set; }
        public string CARDSCHEME { get; set; }
        public string CBN_CODE { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public string MSC_CALCBASIS { get; set; }
        public Nullable<decimal> DOM_MSC1 { get; set; }
        public Nullable<decimal> INT_MSC1 { get; set; }
        public Nullable<decimal> MERCHANTDOMCAP { get; set; }
        public Nullable<decimal> MERCHANTINTLCAP { get; set; }
        public Nullable<decimal> DOM_MSCSUBSIDY { get; set; }
        public Nullable<decimal> INT_MSCSUBSIDY { get; set; }
        public Nullable<decimal> MCCMSC_ITBID { get; set; }
        public string INTMSC_CALCBASIS { get; set; }
        public Nullable<decimal> DOM_MSC2 { get; set; }
        public Nullable<decimal> INT_MSC2 { get; set; }
        public Nullable<decimal> DOM_MSC2CAP { get; set; }
        public Nullable<decimal> INT_MSC2CAP { get; set; }
        public Nullable<decimal> DOM_UNSHAREDMSC { get; set; }
        public Nullable<decimal> INT_UNSHAREDMSC { get; set; }
        public Nullable<decimal> DOM_UNSHAREDCAP { get; set; }
        public Nullable<decimal> INT_UNSHAREDCAP { get; set; }
        public Nullable<decimal> DUE_PERC { get; set; }
        public Nullable<decimal> AMOUNTDUEMERCH_PERC { get; set; }
        public string AMOUNTDUEMERCH_TYPE { get; set; }
        public Nullable<decimal> PERC_ALLOCMERCHANT { get; set; }
        public Nullable<decimal> DIFFCAP { get; set; }
        public string APPLYMERCHANTSHARING { get; set; }
        public Nullable<decimal> COLLECTION { get; set; }
        public Nullable<decimal> FEE1 { get; set; }
        public Nullable<decimal> FEE2 { get; set; }
        public string FEE1_CALCBASIS { get; set; }
        public string FEE2_CALCBASIS { get; set; }
        public string BATCHID { get; set; }
        public string STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<decimal> RECORDID { get; set; }
        public string RowGuid { get; set; }
    }
}
