//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MCCMSC
    {
        public decimal ITBID { get; set; }
        public string CBN_CODE { get; set; }
        public string MCC_CODE { get; set; }
        public string CARDSCHEME { get; set; }
        public Nullable<int> CHANNEL { get; set; }
        public string MSC_CALCBASIS { get; set; }
        public Nullable<decimal> INT_MSCVALUE { get; set; }
        public Nullable<decimal> DOM_MSCVALUE { get; set; }
        public string DOM_SETTLEMENT_CURRENCY { get; set; }
        public string INT_SETTLEMENT_CURRENCY { get; set; }
        public Nullable<int> DOM_FREQUENCY { get; set; }
        public Nullable<int> INT_FREQUENCY { get; set; }
        public Nullable<decimal> DOMCAP { get; set; }
        public Nullable<decimal> INTLCAP { get; set; }
        public string INTMSC_CALCBASIS { get; set; }
        public Nullable<int> SETLLEMETOPTIONID { get; set; }
        public Nullable<decimal> MAXCAPTRANAMOUNT { get; set; }
        public Nullable<decimal> INT_MSCVALUE_WEB { get; set; }
        public Nullable<decimal> DOM_MSCVALUE_WEB { get; set; }
        public Nullable<decimal> DOMCAP_WEB { get; set; }
        public Nullable<decimal> INTLCAP_WEB { get; set; }
        public Nullable<bool> INTL_ENABLED { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> CHANNEL_OLD { get; set; }
    
        public virtual SM_CARDSCHEME SM_CARDSCHEME { get; set; }
        public virtual SM_MCC SM_MCC { get; set; }
    }
}
