//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MERCHANTACCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_MERCHANTACCT()
        {
            this.SM_TERMINAL = new HashSet<SM_TERMINAL>();
            this.SM_REVENUEHEAD = new HashSet<SM_REVENUEHEAD>();
            this.SM_REVENUEGROUP = new HashSet<SM_REVENUEGROUP>();
        }
    
        public decimal ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public string DEPOSIT_BANKCODE { get; set; }
        public string DEPOSIT_ACCOUNTNO { get; set; }
        public string DEPOSIT_BANKNAME { get; set; }
        public string DEPOSIT_COUNTRYCODE { get; set; }
        public string DEPOSIT_ACCTNAME { get; set; }
        public Nullable<bool> DEFAULT_ACCOUNT { get; set; }
        public string DEPOSIT_BANKADDRESS { get; set; }
        public string SETTLEMENTCURRENCY { get; set; }
        public string USERID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string DRBANKCODE { get; set; }
        public string DRACCOUNTNO { get; set; }
        public string DRACCOUNTNAME { get; set; }
    
        public virtual SM_MERCHANTDETAIL SM_MERCHANTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_TERMINAL> SM_TERMINAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_REVENUEHEAD> SM_REVENUEHEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_REVENUEGROUP> SM_REVENUEGROUP { get; set; }
    }
}
