//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MERCHANTTERMINALUPLD
    {
        public decimal ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public string MERCHANTNAME { get; set; }
        public string CONTACTTITLE { get; set; }
        public string CONTACTNAME { get; set; }
        public string MOBILEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string EMAILALERTS { get; set; }
        public string PHYSICALADDR { get; set; }
        public Nullable<decimal> TERMINALMODELCODE { get; set; }
        public string TERMINALID { get; set; }
        public string BANKCODE { get; set; }
        public string BANKACCNO { get; set; }
        public Nullable<decimal> BANKTYPE { get; set; }
        public string SLIPHEADER { get; set; }
        public string SLIPFOOTER { get; set; }
        public string BUISNESSOCCUPATIONCODE { get; set; }
        public string MERCHANTCATEGORYCODE { get; set; }
        public string STATECODE { get; set; }
        public string VISAACQUIRERID { get; set; }
        public string VERVEACQUIRERID { get; set; }
        public string MASTERCARDACQUIRERID { get; set; }
        public string TERMINALOWNERCODE { get; set; }
        public string LGA_LCDA { get; set; }
        public string BANK_URL { get; set; }
        public string ACCOUNTNAME { get; set; }
        public string PTSP { get; set; }
        public string BATCHID { get; set; }
        public string USERID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public string AUTHORIZEID { get; set; }
        public Nullable<int> INSTITUTION_ID { get; set; }
        public Nullable<int> GLOBAL_ITBID { get; set; }
        public Nullable<int> MAKER_INST_ID { get; set; }
        public string INTERFACE_FORMAT { get; set; }
        public string SERVICETYPE { get; set; }
        public Nullable<int> GROUPLABEL { get; set; }
        public string ROWCOLOR { get; set; }
        public string PAYATTITUDE_ACCEPTANCE { get; set; }
        public string TRANSCURRENCY { get; set; }
        public string PTSA { get; set; }
    }
}
