//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MERCHANTDETAILHIST
    {
        public decimal ITBID { get; set; }
        public Nullable<decimal> MERCHANT_ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public string MERCHANTNAME { get; set; }
        public string CONTACTTITLE { get; set; }
        public string CONTACTNAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONENO { get; set; }
        public string ADDRESS { get; set; }
        public string BUSINESS_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string CITY_NAME { get; set; }
        public string MCC_CODE { get; set; }
        public string ACCEPTANCE_TYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string RULE_OPTION { get; set; }
        public string ACQUIRING_CBNCODE { get; set; }
        public string GENERATED { get; set; }
        public string RULE_LOCATOR { get; set; }
        public string MERCHANT_URL { get; set; }
        public Nullable<int> INSTITUTION_ITBID { get; set; }
        public Nullable<decimal> CUSTOMERID { get; set; }
        public string SHORTCODE { get; set; }
        public Nullable<int> COLLECTION { get; set; }
        public Nullable<int> SPECIALMERCHANT { get; set; }
        public Nullable<int> TSA { get; set; }
        public string MAKER_USERID { get; set; }
        public string AUTH_USERID { get; set; }
        public Nullable<System.DateTime> DELETED_DATETIME { get; set; }
    }
}
