//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_NAPS_NIBSS
    {
        public decimal ITBID { get; set; }
        public string DEBITACCTNO { get; set; }
        public string DEBITBANKCODE { get; set; }
        public string BENEFICIARYACCTNO { get; set; }
        public string BENEFICIARYBANKCODE { get; set; }
        public string BENEFICIARYNAME { get; set; }
        public string BENEFICIARYNARRATION { get; set; }
        public Nullable<decimal> CREDITAMOUNT { get; set; }
        public Nullable<System.DateTime> SETTLEMENTDATE { get; set; }
        public string REQUESTTYPE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string BATCHID { get; set; }
        public string STATUS { get; set; }
        public string RESPCODE { get; set; }
        public string RESPMESSAGE { get; set; }
        public string EVENTTYPE { get; set; }
        public string DEBITACCTNO_OLD { get; set; }
        public string DEBITBANKCODE_OLD { get; set; }
        public string BENEFICIARYACCTNO_OLD { get; set; }
        public string BENEFICIARYBANKCODE_OLD { get; set; }
        public string BENEFICIARYNAME_OLD { get; set; }
        public string BENEFICIARYNARRATION_OLD { get; set; }
        public Nullable<decimal> CREDITAMOUNT_OLD { get; set; }
        public string SCHEDULEID { get; set; }
        public string POSTCODE { get; set; }
        public string MERCHANTID { get; set; }
        public string REASON { get; set; }
        public string UNIQUEKEY { get; set; }
    }
}
