//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_PARTYACCOUNT
    {
        public decimal ITBID { get; set; }
        public string DEPOSIT_BANKCODE { get; set; }
        public string DEPOSIT_ACCOUNTNO { get; set; }
        public string DEPOSIT_ACCTNAME { get; set; }
        public string DEPOSIT_BANKNAME { get; set; }
        public string DEPOSIT_COUNTRYCODE { get; set; }
        public string DEPOSIT_BANKADDESS { get; set; }
        public Nullable<bool> DEFAULT_ACCOUNT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public Nullable<int> PARTY_ITBID { get; set; }
        public string BATCHID { get; set; }
        public string AGENT_CODE { get; set; }
    
        public virtual SM_PARTY SM_PARTY { get; set; }
    }
}
