//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_PARTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_PARTY()
        {
            this.SM_PARTYACCOUNT = new HashSet<SM_PARTYACCOUNT>();
        }
    
        public int ITBID { get; set; }
        public string PARTYTYPE_CODE { get; set; }
        public string PARTY_DESC { get; set; }
        public string PARTY_SHORTNAME { get; set; }
        public string PARTY_CODE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_PARTYACCOUNT> SM_PARTYACCOUNT { get; set; }
    }
}
