//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_REVENUEGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_REVENUEGROUP()
        {
            this.SM_REVENUEHEAD = new HashSet<SM_REVENUEHEAD>();
        }
    
        public int ITBID { get; set; }
        public string GROUPCODE { get; set; }
        public string GROUPNAME { get; set; }
        public string MERCHANTID { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public bool GLOBALACCOUNTFLAG { get; set; }
        public Nullable<int> SETTLEMENT_FREQUENCY { get; set; }
        public Nullable<int> SET_DATE_TERM { get; set; }
        public Nullable<int> SET_DAYS { get; set; }
        public Nullable<int> splitrevenue { get; set; }
    
        public virtual SM_MERCHANTACCT SM_MERCHANTACCT { get; set; }
        public virtual SM_MERCHANTDETAIL SM_MERCHANTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_REVENUEHEAD> SM_REVENUEHEAD { get; set; }
    }
}
