//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_REVENUEHEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_REVENUEHEAD()
        {
            this.SM_RevenuHeadParty = new HashSet<SM_RevenuHeadParty>();
            this.SM_RevenuHeadPartyTemp = new HashSet<SM_RevenuHeadPartyTemp>();
        }
    
        public int ITBID { get; set; }
        public string CODE { get; set; }
        public string RVGROUPCODE { get; set; }
        public string ECONOMICSECTOR { get; set; }
        public string DESCRIPTION { get; set; }
        public string BANKCODE { get; set; }
        public string BANKACCOUNT { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public string ACCT_NAME { get; set; }
        public Nullable<decimal> PERCMERCHANT { get; set; }
        public Nullable<decimal> PERCMERCHANT_OTHER { get; set; }
        public Nullable<decimal> PERCMERCHANT_UPSL { get; set; }
        public string APPLYMERCHANTSHARING { get; set; }
        public string AGENT_NAME { get; set; }
        public string RATE_TYPE { get; set; }
        public string AGENT_BANKCODE { get; set; }
        public string AGENT_BANKNAME { get; set; }
        public string AGENT_BANKACCOUNT { get; set; }
        public Nullable<decimal> REVENUCODE_EXCEMPT { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string MERCHANTID { get; set; }
        public Nullable<int> SETTLEMENT_FREQUENCY { get; set; }
        public string REVENUESECTOR { get; set; }
        public Nullable<long> PAYMENTITEMID { get; set; }
    
        public virtual SM_MERCHANTACCT SM_MERCHANTACCT { get; set; }
        public virtual SM_REVENUEGROUP SM_REVENUEGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_RevenuHeadParty> SM_RevenuHeadParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_RevenuHeadPartyTemp> SM_RevenuHeadPartyTemp { get; set; }
    }
}
