//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_REVENUEHEADTEMP
    {
        public decimal ITBID { get; set; }
        public string CODE { get; set; }
        public string MERCHANTID { get; set; }
        public string ECONOMICSECTOR { get; set; }
        public string DESCRIPTION { get; set; }
        public string BANKCODE { get; set; }
        public string BANKACCOUNT { get; set; }
        public Nullable<decimal> PERCMERCHANT { get; set; }
        public Nullable<decimal> PERCMERCHANT_OTHER { get; set; }
        public Nullable<decimal> PERCMERCHANT_UPSL { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string LAST_MODIFIED_AUTHID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string BATCHID { get; set; }
        public Nullable<int> RECORDID { get; set; }
        public string APPLYMERCHANTSHARING { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public string RVGROUPCODE { get; set; }
        public string EVENTTYPE { get; set; }
        public Nullable<int> SETTLEMENT_FREQUENCY { get; set; }
        public string REVENUESECTOR { get; set; }
        public Nullable<long> PAYMENTITEMID { get; set; }
    }
}
