//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SHAREDMSC2DETAILTEMP
    {
        public decimal ITBID { get; set; }
        public string MERCHANTID { get; set; }
        public Nullable<int> PARTYITBID { get; set; }
        public string PARTY_LOCATOR { get; set; }
        public Nullable<decimal> SHARINGVALUE { get; set; }
        public string TRANTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string LASTMODIFIED_UID { get; set; }
        public string BATCHID { get; set; }
        public Nullable<decimal> RECORDID { get; set; }
        public string CARDSCHEME { get; set; }
        public string BANKCODE { get; set; }
        public string BANKACCOUNT { get; set; }
        public Nullable<decimal> MERCHANTMSC_ITBID { get; set; }
        public Nullable<decimal> MCCMSC_ITBID { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public Nullable<decimal> ACCOUNT_ID2 { get; set; }
        public Nullable<decimal> sharingRateAccount1 { get; set; }
        public Nullable<decimal> sharingRateAccount2 { get; set; }
        public Nullable<bool> splitincome { get; set; }
    }
}
