//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_TERMINAL
    {
        public decimal ITBID { get; set; }
        public string TERMINALID { get; set; }
        public string MERCHANTID { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
        public string TERMINALMODEL_CODE { get; set; }
        public string TERMINALOWNER_CODE { get; set; }
        public string SETTLEMENT_CURRENCY { get; set; }
        public string TRANSACTION_CURRENCY { get; set; }
        public Nullable<int> SETTLEMENT_FREQUENCY { get; set; }
        public string PROCESSOR { get; set; }
        public string POINTED { get; set; }
        public string TERMINALDEPLOYEDDATETIME { get; set; }
        public string TERMINALACTIVATNDATETIME { get; set; }
        public string TERMINALCOUNTRY { get; set; }
        public string DEVICETYPE { get; set; }
        public string TERMINALSN { get; set; }
        public string TERMINALTYPECODE { get; set; }
        public string SAMnumeric { get; set; }
        public string DEFAULTIPADDRESS { get; set; }
        public string TERMINALOPERATNSGROUP { get; set; }
        public string DEFAULTOPERATION { get; set; }
        public string GPRSSIMCARDNO { get; set; }
        public string TERMINALSTATUS { get; set; }
        public string GPRSPROVIDERCODE { get; set; }
        public string NETCONECTNCODE { get; set; }
        public string INDICATOR_LOCATION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string USERID { get; set; }
        public string STATUS { get; set; }
        public string BATCHID { get; set; }
        public string LAST_MODIFIED_UID { get; set; }
        public string EMAIL_ALERTS { get; set; }
        public string SLIP_HEADER { get; set; }
        public string SLIP_FOOTER { get; set; }
        public string GENERATED { get; set; }
        public string ACCOUNTNO { get; set; }
        public string INTERFACE_FORMAT { get; set; }
        public string XML_GENERATEDBY { get; set; }
        public Nullable<System.DateTime> XML_GENERATEDDATETIME { get; set; }
        public string PTSA { get; set; }
        public string PTSP { get; set; }
        public string VERVACQUIRERIDNO { get; set; }
        public string MASTACQUIRERIDNO { get; set; }
        public string VISAACQUIRERIDNO { get; set; }
    
        public virtual SM_FREQUENCY SM_FREQUENCY { get; set; }
        public virtual SM_MERCHANTACCT SM_MERCHANTACCT { get; set; }
        public virtual SM_MERCHANTDETAIL SM_MERCHANTDETAIL { get; set; }
    }
}
