//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Generic.Dapper.localhost1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreBankProcessSoap", Namespace="http://tempuri.org/")]
    public partial class CoreBankProcess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BalanceEnquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback MiniStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransactionPostingISOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransactionPostingCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserPasswordAuthLocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthLocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMSPostingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CoreBankProcess() {
            this.Url = global::Generic.Dapper.Properties.Settings.Default.Generic_Dapper_localhost1_CoreBankProcess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BalanceEnquiryCompletedEventHandler BalanceEnquiryCompleted;
        
        /// <remarks/>
        public event MiniStatementCompletedEventHandler MiniStatementCompleted;
        
        /// <remarks/>
        public event TransactionPostingISOCompletedEventHandler TransactionPostingISOCompleted;
        
        /// <remarks/>
        public event TransactionPostingCCCompletedEventHandler TransactionPostingCCCompleted;
        
        /// <remarks/>
        public event CustomerDetailCompletedEventHandler CustomerDetailCompleted;
        
        /// <remarks/>
        public event UserPasswordAuthLocalCompletedEventHandler UserPasswordAuthLocalCompleted;
        
        /// <remarks/>
        public event UserAuthLocalCompletedEventHandler UserAuthLocalCompleted;
        
        /// <remarks/>
        public event SMSPostingCompletedEventHandler SMSPostingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BalanceEnquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BalanceEnquiry(string PAN, string TransRefNo, string TranCode, string AccountNumber) {
            object[] results = this.Invoke("BalanceEnquiry", new object[] {
                        PAN,
                        TransRefNo,
                        TranCode,
                        AccountNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BalanceEnquiryAsync(string PAN, string TransRefNo, string TranCode, string AccountNumber) {
            this.BalanceEnquiryAsync(PAN, TransRefNo, TranCode, AccountNumber, null);
        }
        
        /// <remarks/>
        public void BalanceEnquiryAsync(string PAN, string TransRefNo, string TranCode, string AccountNumber, object userState) {
            if ((this.BalanceEnquiryOperationCompleted == null)) {
                this.BalanceEnquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBalanceEnquiryOperationCompleted);
            }
            this.InvokeAsync("BalanceEnquiry", new object[] {
                        PAN,
                        TransRefNo,
                        TranCode,
                        AccountNumber}, this.BalanceEnquiryOperationCompleted, userState);
        }
        
        private void OnBalanceEnquiryOperationCompleted(object arg) {
            if ((this.BalanceEnquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BalanceEnquiryCompleted(this, new BalanceEnquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MiniStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MiniStatement(string PAN, double TransRefNo, string TranCode, string AccountNumber) {
            object[] results = this.Invoke("MiniStatement", new object[] {
                        PAN,
                        TransRefNo,
                        TranCode,
                        AccountNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string PAN, double TransRefNo, string TranCode, string AccountNumber) {
            this.MiniStatementAsync(PAN, TransRefNo, TranCode, AccountNumber, null);
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string PAN, double TransRefNo, string TranCode, string AccountNumber, object userState) {
            if ((this.MiniStatementOperationCompleted == null)) {
                this.MiniStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMiniStatementOperationCompleted);
            }
            this.InvokeAsync("MiniStatement", new object[] {
                        PAN,
                        TransRefNo,
                        TranCode,
                        AccountNumber}, this.MiniStatementOperationCompleted, userState);
        }
        
        private void OnMiniStatementOperationCompleted(object arg) {
            if ((this.MiniStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MiniStatementCompleted(this, new MiniStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransactionPostingISO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TransactionPostingISO(string PAN, string TransRefNo, string DebitAccountNumber, string CreditAccountNumber, string Narration, string TranCode, System.DateTime ValueDate, string Amount) {
            object[] results = this.Invoke("TransactionPostingISO", new object[] {
                        PAN,
                        TransRefNo,
                        DebitAccountNumber,
                        CreditAccountNumber,
                        Narration,
                        TranCode,
                        ValueDate,
                        Amount});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TransactionPostingISOAsync(string PAN, string TransRefNo, string DebitAccountNumber, string CreditAccountNumber, string Narration, string TranCode, System.DateTime ValueDate, string Amount) {
            this.TransactionPostingISOAsync(PAN, TransRefNo, DebitAccountNumber, CreditAccountNumber, Narration, TranCode, ValueDate, Amount, null);
        }
        
        /// <remarks/>
        public void TransactionPostingISOAsync(string PAN, string TransRefNo, string DebitAccountNumber, string CreditAccountNumber, string Narration, string TranCode, System.DateTime ValueDate, string Amount, object userState) {
            if ((this.TransactionPostingISOOperationCompleted == null)) {
                this.TransactionPostingISOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransactionPostingISOOperationCompleted);
            }
            this.InvokeAsync("TransactionPostingISO", new object[] {
                        PAN,
                        TransRefNo,
                        DebitAccountNumber,
                        CreditAccountNumber,
                        Narration,
                        TranCode,
                        ValueDate,
                        Amount}, this.TransactionPostingISOOperationCompleted, userState);
        }
        
        private void OnTransactionPostingISOOperationCompleted(object arg) {
            if ((this.TransactionPostingISOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransactionPostingISOCompleted(this, new TransactionPostingISOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransactionPostingCC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TransactionPostingCC(string TransRefNo, string TranCode, string TellerNo, string DebitAccountNumber, string Narration, decimal Amount, decimal TranCharge, System.DateTime ValueDate, string UserId) {
            object[] results = this.Invoke("TransactionPostingCC", new object[] {
                        TransRefNo,
                        TranCode,
                        TellerNo,
                        DebitAccountNumber,
                        Narration,
                        Amount,
                        TranCharge,
                        ValueDate,
                        UserId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TransactionPostingCCAsync(string TransRefNo, string TranCode, string TellerNo, string DebitAccountNumber, string Narration, decimal Amount, decimal TranCharge, System.DateTime ValueDate, string UserId) {
            this.TransactionPostingCCAsync(TransRefNo, TranCode, TellerNo, DebitAccountNumber, Narration, Amount, TranCharge, ValueDate, UserId, null);
        }
        
        /// <remarks/>
        public void TransactionPostingCCAsync(string TransRefNo, string TranCode, string TellerNo, string DebitAccountNumber, string Narration, decimal Amount, decimal TranCharge, System.DateTime ValueDate, string UserId, object userState) {
            if ((this.TransactionPostingCCOperationCompleted == null)) {
                this.TransactionPostingCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransactionPostingCCOperationCompleted);
            }
            this.InvokeAsync("TransactionPostingCC", new object[] {
                        TransRefNo,
                        TranCode,
                        TellerNo,
                        DebitAccountNumber,
                        Narration,
                        Amount,
                        TranCharge,
                        ValueDate,
                        UserId}, this.TransactionPostingCCOperationCompleted, userState);
        }
        
        private void OnTransactionPostingCCOperationCompleted(object arg) {
            if ((this.TransactionPostingCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransactionPostingCCCompleted(this, new TransactionPostingCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CustomerDetail(string AcctNo) {
            object[] results = this.Invoke("CustomerDetail", new object[] {
                        AcctNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerDetailAsync(string AcctNo) {
            this.CustomerDetailAsync(AcctNo, null);
        }
        
        /// <remarks/>
        public void CustomerDetailAsync(string AcctNo, object userState) {
            if ((this.CustomerDetailOperationCompleted == null)) {
                this.CustomerDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerDetailOperationCompleted);
            }
            this.InvokeAsync("CustomerDetail", new object[] {
                        AcctNo}, this.CustomerDetailOperationCompleted, userState);
        }
        
        private void OnCustomerDetailOperationCompleted(object arg) {
            if ((this.CustomerDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerDetailCompleted(this, new CustomerDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserPasswordAuthLocal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UserPasswordAuthLocal(string UserId, string Password) {
            object[] results = this.Invoke("UserPasswordAuthLocal", new object[] {
                        UserId,
                        Password});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UserPasswordAuthLocalAsync(string UserId, string Password) {
            this.UserPasswordAuthLocalAsync(UserId, Password, null);
        }
        
        /// <remarks/>
        public void UserPasswordAuthLocalAsync(string UserId, string Password, object userState) {
            if ((this.UserPasswordAuthLocalOperationCompleted == null)) {
                this.UserPasswordAuthLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserPasswordAuthLocalOperationCompleted);
            }
            this.InvokeAsync("UserPasswordAuthLocal", new object[] {
                        UserId,
                        Password}, this.UserPasswordAuthLocalOperationCompleted, userState);
        }
        
        private void OnUserPasswordAuthLocalOperationCompleted(object arg) {
            if ((this.UserPasswordAuthLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserPasswordAuthLocalCompleted(this, new UserPasswordAuthLocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAuthLocal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UserAuthLocal(string UserId) {
            object[] results = this.Invoke("UserAuthLocal", new object[] {
                        UserId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthLocalAsync(string UserId) {
            this.UserAuthLocalAsync(UserId, null);
        }
        
        /// <remarks/>
        public void UserAuthLocalAsync(string UserId, object userState) {
            if ((this.UserAuthLocalOperationCompleted == null)) {
                this.UserAuthLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthLocalOperationCompleted);
            }
            this.InvokeAsync("UserAuthLocal", new object[] {
                        UserId}, this.UserAuthLocalOperationCompleted, userState);
        }
        
        private void OnUserAuthLocalOperationCompleted(object arg) {
            if ((this.UserAuthLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthLocalCompleted(this, new UserAuthLocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMSPosting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SMSPosting(string CASAAcct, string narration) {
            object[] results = this.Invoke("SMSPosting", new object[] {
                        CASAAcct,
                        narration});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SMSPostingAsync(string CASAAcct, string narration) {
            this.SMSPostingAsync(CASAAcct, narration, null);
        }
        
        /// <remarks/>
        public void SMSPostingAsync(string CASAAcct, string narration, object userState) {
            if ((this.SMSPostingOperationCompleted == null)) {
                this.SMSPostingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMSPostingOperationCompleted);
            }
            this.InvokeAsync("SMSPosting", new object[] {
                        CASAAcct,
                        narration}, this.SMSPostingOperationCompleted, userState);
        }
        
        private void OnSMSPostingOperationCompleted(object arg) {
            if ((this.SMSPostingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMSPostingCompleted(this, new SMSPostingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BalanceEnquiryCompletedEventHandler(object sender, BalanceEnquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BalanceEnquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BalanceEnquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void MiniStatementCompletedEventHandler(object sender, MiniStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MiniStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MiniStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransactionPostingISOCompletedEventHandler(object sender, TransactionPostingISOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransactionPostingISOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransactionPostingISOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransactionPostingCCCompletedEventHandler(object sender, TransactionPostingCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransactionPostingCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransactionPostingCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CustomerDetailCompletedEventHandler(object sender, CustomerDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UserPasswordAuthLocalCompletedEventHandler(object sender, UserPasswordAuthLocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserPasswordAuthLocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserPasswordAuthLocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UserAuthLocalCompletedEventHandler(object sender, UserAuthLocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthLocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthLocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SMSPostingCompletedEventHandler(object sender, SMSPostingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMSPostingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMSPostingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591