using Generic.Data.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Generic.Dapper.Model
{
    public partial class SM_SETTLEMENTDETAIL
    {
        public decimal ITBID { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<decimal> DOCNO { get; set; }
        public string REFNO { get; set; }
        public Nullable<int> CHANNELID { get; set; }
        public string CARDSCHEME { get; set; }
        public string TRANCODE { get; set; }
        public string TRANDESC { get; set; }
        public string TRANDATETIME { get; set; }
        public string ISSUERFIID { get; set; }
        public string ISSUERCURRENCY { get; set; }
        public string ACQUIRERFIID { get; set; }
        public string ACQUIRERCURRENCY { get; set; }
        public string MASKEDPAN { get; set; }
        public string PAN { get; set; }
        public Nullable<System.DateTime> EXPDATETIME { get; set; }
        public Nullable<System.DateTime> SETTLEMENTDATETIME { get; set; }
        public string APPROVALCODE { get; set; }
        public string APPROVALMESSAGE { get; set; }
        public string TERMINALID { get; set; }
        public string MERCHANTID { get; set; }
        public string MERCHANTNAME { get; set; }
        public string TRANSID { get; set; }
        public string MERCHANTLOCATION { get; set; }
        public string MERCHANTDEPOSITBANK { get; set; }
        public string MERCHANTDEPOSITBANKCODE { get; set; }
        public string MERCHANTDEPOSITBANKACCTNO { get; set; }
        public string MCC { get; set; }
        public string MCC_DESCRIPTION { get; set; }
        public string STAN { get; set; }
        public string INVOICENO { get; set; }
        public string CUSTOMERNAME { get; set; }
        public Nullable<decimal> ORGINALAMOUNT { get; set; }
        public Nullable<decimal> ORGINALCURRENCY { get; set; }
        public Nullable<decimal> TRANAMOUNT { get; set; }
        public Nullable<decimal> TRANCURRENCY { get; set; }
        public string SIGN { get; set; }
        public Nullable<decimal> ISSUERFEE { get; set; }
        public Nullable<decimal> ISSUERFEECURRENCY { get; set; }
        public Nullable<decimal> ACQUIRERFEE { get; set; }
        public Nullable<decimal> ACQUIRERFEECURRENCY { get; set; }
        public string ACQUIRER_REF { get; set; }
        public Nullable<decimal> SETTLEMENTCURRENCY { get; set; }
        public Nullable<decimal> MSC1_RATE { get; set; }
        public Nullable<decimal> MSC1_CAP { get; set; }
        public Nullable<decimal> MSC2_RATE { get; set; }
        public Nullable<decimal> MSC2_CAP { get; set; }
        public Nullable<decimal> SHARINGMSC1_RATE { get; set; }
        public Nullable<decimal> UNSHAREDMSC1_RATE { get; set; }
        public Nullable<decimal> SUBSIDY_RATE { get; set; }
        public Nullable<decimal> MSC1_AMOUNT { get; set; }
        public Nullable<decimal> MSC2_AMOUNT { get; set; }
        public Nullable<decimal> TOTALMSC_AMOUNT { get; set; }
        public Nullable<decimal> EFFECTIVEMSC { get; set; }
        public Nullable<decimal> SHARINGMSC1_AMOUNT { get; set; }
        public Nullable<decimal> UNSHAREDMSC1_AMOUNT { get; set; }
        public string MSC2_SPLITSHARING { get; set; }
        public string MSC2_SPLITSHARINGACCT { get; set; }
        public Nullable<decimal> PERC_ALLOTOTHERS { get; set; }
        public Nullable<decimal> PERC_ALLOTHOLDER { get; set; }
        public Nullable<decimal> SUBSIDY_AMOUNT { get; set; }
        public Nullable<decimal> PERC_ALLOTMERCHANT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNTDUE { get; set; }
        public Nullable<decimal> DEDUCTION_AMOUNTDUE { get; set; }
        public Nullable<decimal> NET_AMOUNTDUEMERCHANT { get; set; }
        public Nullable<decimal> IRF { get; set; }
        public string SPECIALCARD { get; set; }
        public string SPECIALCARD_OWNER { get; set; }
        public string REASONFORALTERATION { get; set; }
        public string FULLREM_TRANSLATION { get; set; }
        public Nullable<decimal> TRACENO { get; set; }
        public Nullable<decimal> HOST { get; set; }
        public string ORIGID { get; set; }
        public string EXTRRN { get; set; }
        public string ORIGTYPE { get; set; }
        public string INVOICENUM { get; set; }
        public string SEQNUM { get; set; }
        public Nullable<decimal> LCYAMOUNT { get; set; }
        public Nullable<decimal> FCYAMOUNT { get; set; }
        public Nullable<decimal> EXCHANGERATE { get; set; }
        public string SETTLEMENTACCOUNT { get; set; }
        public Nullable<decimal> SETTLEMENTAMOUNT { get; set; }
        public Nullable<decimal> REVERSEREQID { get; set; }
        public string SECTORCODE { get; set; }
        public string SECTOR { get; set; }
        public string TRANXSAVED { get; set; }
        public string CARDCOUNTRY { get; set; }
        public Nullable<decimal> PROCESSINGFEE { get; set; }
        public string CUSTOMERACCOUNT { get; set; }
        public string PHONENO { get; set; }
        public string ACQR_CODE { get; set; }
        public string ACQR_NAME { get; set; }
        public Nullable<decimal> ACQR_RATE { get; set; }
        public Nullable<decimal> ACQR_VALUE { get; set; }
        public string ACQR_ACCOUNT { get; set; }
        public string ISSR_CODE { get; set; }
        public string ISSR_NAME { get; set; }
        public Nullable<decimal> ISSR_RATE { get; set; }
        public Nullable<decimal> ISSR_VALUE { get; set; }
        public string ISSR_ACCOUNT { get; set; }
        public string PTSP_CODE { get; set; }
        public string PTSP_NAME { get; set; }
        public Nullable<decimal> PTSP_RATE { get; set; }
        public Nullable<decimal> PTSP_VALUE { get; set; }
        public string PTSP_ACCOUNT { get; set; }
        public string PTSA_CODE { get; set; }
        public string PTSA_NAME { get; set; }
        public Nullable<decimal> PTSA_RATE { get; set; }
        public Nullable<decimal> PTSA_VALUE { get; set; }
        public string PTSA_ACCOUNT { get; set; }
        public string TERW_CODE { get; set; }
        public string TERW_NAME { get; set; }
        public Nullable<decimal> TERW_RATE { get; set; }
        public Nullable<decimal> TERW_VALUE { get; set; }
        public string TERW_ACCOUNT { get; set; }
        public string SWTH_CODE { get; set; }
        public string SWTH_NAME { get; set; }
        public Nullable<decimal> SWTH_RATE { get; set; }
        public Nullable<decimal> SWTH_VALUE { get; set; }
        public string SWTH_ACCOUNT { get; set; }
        public string BILR_CODE { get; set; }
        public string BILR_NAME { get; set; }
        public Nullable<decimal> BILR_RATE { get; set; }
        public Nullable<decimal> BILR_VALUE { get; set; }
        public string BILR_ACCOUNT { get; set; }
        public string TECH_CODE { get; set; }
        public string TECH_NAME { get; set; }
        public Nullable<decimal> TECH_RATE { get; set; }
        public Nullable<decimal> TECH_VALUE { get; set; }
        public string TECH_ACCOUNT { get; set; }
        public string COAQ_CODE { get; set; }
        public string COAQ_NAME { get; set; }
        public Nullable<decimal> COAQ_RATE { get; set; }
        public Nullable<decimal> COAQ_VALUE { get; set; }
        public string COAQ_ACCOUNT { get; set; }
        public string REVW_CODE { get; set; }
        public string REVW_NAME { get; set; }
        public Nullable<decimal> REVW_RATE { get; set; }
        public Nullable<decimal> REVW_VALUE { get; set; }
        public string REVW_ACCOUNT { get; set; }
        public string GOVT_CODE { get; set; }
        public string GOVT_NAME { get; set; }
        public Nullable<decimal> GOVT_RATE { get; set; }
        public Nullable<decimal> GOVT_VALUE { get; set; }
        public string GOVT_ACCOUNT { get; set; }
        public string AGNT_CODE { get; set; }
        public string AGNT_NAME { get; set; }
        public Nullable<decimal> AGNT_RATE { get; set; }
        public Nullable<decimal> AGNT_VALUE { get; set; }
        public string AGNT_ACCOUNT { get; set; }
        public string VEND_CODE { get; set; }
        public string VEND_NAME { get; set; }
        public Nullable<decimal> VEND_RATE { get; set; }
        public Nullable<decimal> VEND_VALUE { get; set; }
        public string VEND_ACCOUNT { get; set; }
        public string BLLR_CODE { get; set; }
        public string BLLR_NAME { get; set; }
        public Nullable<decimal> BLLR_RATE { get; set; }
        public Nullable<decimal> BLLR_VALUE { get; set; }
        public string BLLR_ACCOUNT { get; set; }
        public string SERVICEPROVIDER { get; set; }
        public string SERVICEPROVIDERBANKCODE { get; set; }
        public string SERVICEPROVIDERBANK { get; set; }
        public string SERVICEPROVIDERACCOUNTNO { get; set; }
        public string BENEFICIARYNAME { get; set; }
        public string BENEFICIARYBANKCODE { get; set; }
        public string BENEFICIARYBANK { get; set; }
        public string BENEFICIARYACCOUNTNO { get; set; }
        public Nullable<decimal> INTERCHANGEFEE { get; set; }
        public Nullable<decimal> INTERCHANGEFEECUR { get; set; }
        public string SPECIALMESSAGE1 { get; set; }
        public string SPECIALMESSAGE2 { get; set; }
        public string SPECIALMESSAGE3 { get; set; }
        public string SPECIALMESSAGE4 { get; set; }
        public string SOURCEDB { get; set; }
        public string SOURCETABLE { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> RECORDID { get; set; }
        public Nullable<decimal> BATCHNO { get; set; }
        public string PROCESS_STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string PAYMENTREFERENCE { get; set; }
        public string SETTLEMENTID { get; set; }
        public string LOCATION { get; set; }
        public string SETDATE { get { return SETTLEMENTDATETIME.GetValueOrDefault().ToString("dd-MM-yyyy"); } }
        public string VALDATE { get { return VALUEDATE.GetValueOrDefault().ToString("dd-MM-yyyy"); } }
        public string TRANAMT { get { return SmartObj.FormatMoney(TRANAMOUNT.GetValueOrDefault().ToString()); } }
        public DateTime? VALUEDATE { get; set; }
    }
}
